export const DASHBOARD_MOBILE_TAILWIND_CLASS = [
  "w-full min-w-0 max-w-full overflow-x-clip",
  "[&>div]:w-full [&>div]:min-w-0 [&>div]:max-w-full",
  "[&>div>*+*]:!mt-2.5",
  "[&_[data-slot='card']]:min-w-0 [&_[data-slot='card']]:!rounded-[.875rem]",
  "[&_[data-slot='card-header']]:min-w-0 [&_[data-slot='card-content']]:min-w-0",
  "[&_.recharts-responsive-container]:!max-w-full [&_.recharts-wrapper]:!max-w-full [&_.recharts-surface]:!max-w-full",
  "max-lg:[&>div>section:first-of-type]:!py-1",
  "max-lg:[&>div>section:first-of-type_h1]:!text-[clamp(1.5rem,7vw,1.85rem)] max-lg:[&>div>section:first-of-type_h1]:!leading-[1.08]",
  "max-lg:[&>div>section:first-of-type_p]:!mt-[.4rem] max-lg:[&>div>section:first-of-type_p]:!text-[.82rem]",
  "max-lg:[&>div>[data-slot='card']:first-of-type]:!h-[255px] max-lg:[&>div>[data-slot='card']:first-of-type]:!min-h-[255px]",
  "max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-header']]:!p-[1rem_1rem_.25rem]",
  "max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-header']>div:first-child]:!pr-[6.75rem]",
  "max-lg:[&>div>[data-slot='card']:first-of-type_[data-slot='card-description']]:!text-[.82rem] max-lg:[&>div>[data-slot='card']:first-of-type_[data-slot='card-description']]:!leading-4",
  "max-lg:[&>div>[data-slot='card']:first-of-type_[data-slot='card-title']]:!mt-1 max-lg:[&>div>[data-slot='card']:first-of-type_[data-slot='card-title']]:!text-[clamp(1.85rem,9vw,2.2rem)] max-lg:[&>div>[data-slot='card']:first-of-type_[data-slot='card-title']]:!leading-none",
  "max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-header']_p:last-child]:!mt-[.55rem] max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-header']_p:last-child]:!text-[.78rem]",
  "max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-header']>div:last-child]:!top-[1.1rem] max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-header']>div:last-child]:!right-4 max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-header']>div:last-child]:!rounded-[.65rem] max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-header']>div:last-child]:!p-[.48rem_.72rem] max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-header']>div:last-child]:!text-[.82rem]",
  "max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-content']]:!h-[150px] max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-content']]:!min-h-[150px] max-lg:[&>div>[data-slot='card']:first-of-type>[data-slot='card-content']]:!pt-1",
  "max-lg:[&>div>section:nth-of-type(2)]:!grid-cols-2 max-lg:[&>div>section:nth-of-type(2)]:!gap-2",
  "max-lg:[&>div>section:nth-of-type(2)>[data-slot='card']]:!min-h-[198px]",
  "max-lg:[&>div>section:nth-of-type(2)_[data-slot='card-header']]:!p-[.9rem_.8rem_0]",
  "max-lg:[&>div>section:nth-of-type(2)_[data-slot='card-title']]:truncate max-lg:[&>div>section:nth-of-type(2)_[data-slot='card-title']]:!text-[.78rem] max-lg:[&>div>section:nth-of-type(2)_[data-slot='card-title']]:!leading-4",
  "max-lg:[&>div>section:nth-of-type(2)_[data-slot='card-content']]:!p-[.9rem_.8rem_.75rem]",
  "max-lg:[&>div>section:nth-of-type(2)_[data-slot='card-content']>p:first-child]:!text-[clamp(1.7rem,7.8vw,2.05rem)] max-lg:[&>div>section:nth-of-type(2)_[data-slot='card-content']>p:first-child]:!leading-none",
  "max-lg:[&>div>section:nth-of-type(2)>[data-slot='card']:nth-child(-n+2)]:!min-h-[202px]",
  "max-lg:[&>div>section:nth-of-type(2)>[data-slot='card']:nth-child(n+3)]:!min-h-[176px]",
  "max-[359px]:[&>div>section:nth-of-type(2)]:!gap-[.4rem]",
  "max-[359px]:[&>div>section:nth-of-type(2)_[data-slot='card-header']]:!px-[.65rem] max-[359px]:[&>div>section:nth-of-type(2)_[data-slot='card-content']]:!px-[.65rem]",
  "max-[359px]:[&>div>section:nth-of-type(2)_[data-slot='card-title']]:!text-[.7rem]",
].join(" ");
