"use client";

import { LoaderCircle, Play, Server } from "lucide-react";
import { useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { apiRequest } from "@/lib/api-client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "./auth-context";
import type { BacktestResult } from "./types";

interface Run { id:string; asset:string; strategy:string; timeframe:string; period:string; net_return:string; win_rate:string; profit_factor:string; created_at:string }
export function Backtest() {
  const { user } = useAuth();
  const [result,setResult]=useState<BacktestResult|null>(null); const [runs,setRuns]=useState<Run[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  const [form,setForm]=useState({asset:"BTC/USDT",strategy:"EMA Crossover",timeframe:"4 soat",period:"2 yil",initialBalance:10000,riskPercent:1});
  useEffect(()=>{apiRequest<{runs:Run[]}>("/api/backtests").then(d=>setRuns(d.runs)).catch(()=>setRuns([]));},[user]);
  const run=async()=>{setLoading(true);setError(null);try{const d=await apiRequest<{result:BacktestResult}>("/api/backtests",{method:"POST",body:JSON.stringify(form)});setResult(d.result);if(user){const h=await apiRequest<{runs:Run[]}>("/api/backtests");setRuns(h.runs);}}catch(e){setError(e instanceof Error?e.message:"Backtest bajarilmadi");}finally{setLoading(false);}};
  const set=(key:string,value:string|number)=>setForm(v=>({...v,[key]:value}));
  return <><header className="sticky top-0 z-10 flex h-14 items-center border-b border-white/8 bg-[#0c1424]/32 px-4 backdrop-blur-2xl"><div><h1 className="text-xl font-extrabold">Strategiya backtesti</h1><p className="text-xs text-xmuted">Node.js hisoblash serveri</p></div><span className="ml-auto flex items-center gap-1 text-xs text-emerald-400"><Server size={14}/>Online</span></header>
  <div className="space-y-4 p-4">{error&&<div className="rounded-lg bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}<section className="rounded-2xl border border-white/9 bg-white/[.035] p-4 backdrop-blur-2xl"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["asset",["BTC/USDT","ETH/USDT","XAU/USD"]],["strategy",["EMA Crossover","Breakout","RSI Reversal"]],["timeframe",["15 daqiqa","1 soat","4 soat","1 kun"]],["period",["2 yil","3 yil","5 yil"]]].map(([key,opts])=><label key={String(key)} className="text-xs text-xmuted">{String(key)}<select value={String(form[key as keyof typeof form])} onChange={e=>set(String(key),e.target.value)} className="mt-1 h-9 w-full rounded-md border border-white/10 bg-[#111a2a]/65 px-3 text-white backdrop-blur-xl">{(opts as string[]).map(o=><option key={o}>{o}</option>)}</select></label>)}<label className="text-xs text-xmuted">Balans<Input type="number" value={form.initialBalance} onChange={e=>set("initialBalance",+e.target.value)}/></label><label className="text-xs text-xmuted">Risk %<Input type="number" step=".1" max="5" value={form.riskPercent} onChange={e=>set("riskPercent",+e.target.value)}/></label></div><Button onClick={()=>void run()} disabled={loading} className="mt-4 rounded-full bg-xblue text-white">{loading?<LoaderCircle className="animate-spin"/>:<Play/>}Backtestni boshlash</Button></section>
  {result&&<><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["Net return",`${result.netReturn}%`],["Win rate",`${result.winRate}%`],["Drawdown",`-${result.maxDrawdown}%`],["Profit factor",`${result.profitFactor}`]].map(([l,v])=><div key={l} className="rounded-2xl border border-white/9 bg-white/[.035] p-4 backdrop-blur-2xl"><p className="text-xs text-xmuted">{l}</p><p className="mt-2 font-mono text-2xl font-bold">{v}</p></div>)}</div><section className="rounded-2xl border border-white/9 bg-white/[.035] p-4 backdrop-blur-2xl"><h2 className="font-bold">Equity curve · {result.tradesCount} trade</h2><div className="mt-4 h-72"><ResponsiveContainer><AreaChart data={result.equityCurve}><CartesianGrid stroke="#263653" vertical={false}/><XAxis dataKey="step" stroke="#91a0b8"/><YAxis stroke="#91a0b8"/><Tooltip contentStyle={{background:"#101a2ddd",border:"1px solid #263653"}}/><Area dataKey="equity" stroke="#4f8cff" fill="#4f8cff33"/></AreaChart></ResponsiveContainer></div></section></>}
  <section className="rounded-2xl border border-white/9 bg-white/[.025] backdrop-blur-2xl"><h2 className="border-b border-white/8 p-4 font-bold">Saqlangan natijalar</h2>{!runs.length?<p className="p-8 text-center text-sm text-xmuted">{user?"Hali natija yo'q.":"Kirsangiz natijalar saqlanadi."}</p>:runs.map(r=><div key={r.id} className="flex items-center border-b border-white/8 p-3 last:border-0"><div><b>{r.asset} · {r.strategy}</b><p className="text-xs text-xmuted">{new Date(r.created_at).toLocaleDateString("uz-UZ")}</p></div><span className="ml-auto font-mono text-emerald-400">{+r.net_return>0?"+":""}{r.net_return}%</span></div>)}</section></div></>;
}
