"use client";

import { ArrowLeft,BarChart3,CalendarDays,ChevronRight,Download,ImageIcon,LoaderCircle,Plus,Search,ShieldCheck,Target,TrendingDown,TrendingUp,WalletCards } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import { Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { apiRequest } from "@/lib/api-client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardDescription,CardFooter,CardHeader,CardTitle } from "@/components/ui/card";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "./auth-context";
import { PropAccountDialog } from "./prop-account-dialog";
import type { JournalEntry,PropAccount } from "./types";

type AccountRecord={id:string;name:string;firm:string;phase:string;market_type:string;account_size:string;initial_balance:string;profit_target:string;max_drawdown:string;daily_drawdown:string;start_date:string;status:PropAccount["status"]};
type EntryRecord={id:string;prop_account_id?:string|null;symbol:string;side:"Long"|"Short";entry_price:string;exit_price:string;quantity:string;fees:string;pnl:string;note:string;traded_at:string;account_name?:string;market_type?:string;setup?:string;emotion?:string;risk_amount?:string;result_r?:string;image_url?:string|null;tags?:string[]};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2});
const days=["Du","Se","Cho","Pa","Ju","Sha","Ya"];
const mapAccount=(a:AccountRecord):PropAccount=>({id:a.id,name:a.name,firm:a.firm,phase:a.phase,marketType:a.market_type,accountSize:Number(a.account_size),initialBalance:Number(a.initial_balance),profitTarget:Number(a.profit_target),maxDrawdown:Number(a.max_drawdown),dailyDrawdown:Number(a.daily_drawdown),startDate:a.start_date,status:a.status});
const mapEntry=(e:EntryRecord):JournalEntry=>({id:e.id,propAccountId:e.prop_account_id,symbol:e.symbol,side:e.side,entry:Number(e.entry_price),exit:Number(e.exit_price),quantity:Number(e.quantity),fees:Number(e.fees),pnl:Number(e.pnl),note:e.note,rawDate:e.traded_at,date:new Date(`${e.traded_at}T00:00:00`).toLocaleDateString("uz-UZ"),accountName:e.account_name,marketType:e.market_type,setup:e.setup||"",emotion:e.emotion||"Neutral",riskAmount:Number(e.risk_amount||0),resultR:Number(e.result_r||0),imageUrl:e.image_url,tags:e.tags||[]});
const monthKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`;

export function Journal({onLogin}:{onLogin:()=>void}){
 const {user}=useAuth();
 const [accounts,setAccounts]=useState<PropAccount[]>([]),[entries,setEntries]=useState<JournalEntry[]>([]),[accountId,setAccountId]=useState<string|null>(null);
 const [accountOpen,setAccountOpen]=useState(false),[tradeOpen,setTradeOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[query,setQuery]=useState(""),[month]=useState(new Date());
 useEffect(()=>{if(!user)return;let active=true;Promise.all([apiRequest<{accounts:AccountRecord[]}>("/api/prop-accounts"),apiRequest<{entries:EntryRecord[]}>("/api/journal")]).then(([a,e])=>{if(active){setAccounts(a.accounts.map(mapAccount));setEntries(e.entries.map(mapEntry));}}).catch((e:Error)=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false};},[user]);
 const selected=accounts.find(a=>a.id===accountId)||null;
 const selectedEntries=useMemo(()=>entries.filter(e=>e.propAccountId===accountId),[entries,accountId]);
 const monthEntries=useMemo(()=>selectedEntries.filter(e=>e.rawDate?.startsWith(monthKey(month))),[selectedEntries,month]);
 const visible=useMemo(()=>{const q=query.toLowerCase().trim();return q?monthEntries.filter(e=>`${e.symbol} ${e.setup} ${e.note} ${e.tags?.join(" ")}`.toLowerCase().includes(q)):monthEntries;},[monthEntries,query]);
 const summaries=useMemo(()=>accounts.map(account=>{const trades=entries.filter(e=>e.propAccountId===account.id),pnl=trades.reduce((s,e)=>s+e.pnl,0),wins=trades.filter(e=>e.pnl>0).length;return{account,trades:trades.length,pnl,winRate:trades.length?Math.round(wins/trades.length*100):0,target:account.profitTarget?Math.min(100,Math.max(0,pnl/account.profitTarget*100)):0,dd:account.maxDrawdown&&pnl<0?Math.min(100,Math.abs(pnl)/account.maxDrawdown*100):0};}),[accounts,entries]);
 const stats=useMemo(()=>{const pnl=monthEntries.reduce((s,e)=>s+e.pnl,0),wins=monthEntries.filter(e=>e.pnl>0),losses=monthEntries.filter(e=>e.pnl<0),gw=wins.reduce((s,e)=>s+e.pnl,0),gl=Math.abs(losses.reduce((s,e)=>s+e.pnl,0));return{pnl,wins:wins.length,losses:losses.length,winRate:monthEntries.length?Math.round(wins.length/monthEntries.length*100):0,avgR:monthEntries.length?monthEntries.reduce((s,e)=>s+(e.resultR||0),0)/monthEntries.length:0,pf:gl?gw/gl:gw?gw:0};},[monthEntries]);
 const equity=useMemo(()=>{let value=selected?.initialBalance||0;return [...selectedEntries].sort((a,b)=>String(a.rawDate).localeCompare(String(b.rawDate))).map((e,i)=>({trade:i+1,equity:value+=e.pnl}));},[selectedEntries,selected]);
 const setups=useMemo(()=>{const map=new Map<string,{pnl:number;trades:number;wins:number}>();monthEntries.forEach(e=>{const k=e.setup||"Uncategorized",v=map.get(k)||{pnl:0,trades:0,wins:0};map.set(k,{pnl:v.pnl+e.pnl,trades:v.trades+1,wins:v.wins+(e.pnl>0?1:0)});});return [...map].map(([name,v])=>({name,...v,rate:Math.round(v.wins/v.trades*100)})).sort((a,b)=>b.pnl-a.pnl);},[monthEntries]);
 const calendar=useMemo(()=>{const y=month.getFullYear(),m=month.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,count=new Date(y,m+1,0).getDate();return Array.from({length:42},(_,i)=>{const day=i-offset+1;if(day<1||day>count)return null;const key=`${monthKey(month)}-${String(day).padStart(2,"0")}`,trades=selectedEntries.filter(e=>e.rawDate===key);return{day,trades,pnl:trades.reduce((s,e)=>s+e.pnl,0)};});},[month,selectedEntries]);
 async function saveAccount(form:FormData){setSaving(true);try{const {account}=await apiRequest<{account:AccountRecord}>("/api/prop-accounts",{method:"POST",body:JSON.stringify(Object.fromEntries(form))});const next=mapAccount(account);setAccounts(v=>[next,...v]);setAccountOpen(false);setAccountId(next.id);}catch(e){setError(e instanceof Error?e.message:"Account saqlanmadi");}finally{setSaving(false);}}
 async function saveTrade(form:FormData){if(!selected)return;setSaving(true);try{const {entry}=await apiRequest<{entry:EntryRecord}>("/api/journal",{method:"POST",body:JSON.stringify({propAccountId:selected.id,symbol:form.get("symbol"),side:form.get("side"),entry:Number(form.get("entry")),exit:Number(form.get("exit")),quantity:Number(form.get("quantity")),fees:Number(form.get("fees")),riskAmount:Number(form.get("riskAmount")),tradedAt:form.get("tradedAt"),setup:form.get("setup"),emotion:form.get("emotion"),tags:String(form.get("tags")||"").split(","),note:form.get("note")})});setEntries(v=>[mapEntry(entry),...v]);setTradeOpen(false);}catch(e){setError(e instanceof Error?e.message:"Trade saqlanmadi");}finally{setSaving(false);}}
 function csv(){const rows=[["Date","Symbol","Side","PnL","R","Setup"],...visible.map(e=>[e.rawDate,e.symbol,e.side,e.pnl,e.resultR,e.setup])];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(v=>`"${v||""}"`).join(",")).join("\n")],{type:"text/csv"}));a.download=`${selected?.name||"journal"}.csv`;a.click();URL.revokeObjectURL(a.href);}
 if(!user)return <div className="grid min-h-[75dvh] place-items-center text-center"><div><Target className="mx-auto text-cyan-300" size={42}/><h2 className="mt-4 text-2xl font-black">Professional trading jurnal</h2><Button className="mt-5" onClick={onLogin}>Google orqali kirish</Button></div></div>;
 if(loading)return <div className="grid min-h-[70dvh] place-items-center"><LoaderCircle className="animate-spin"/></div>;
 return <div className="min-h-full">{error&&<div className="m-4 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</div>}
 {!selected?<AllAccounts summaries={summaries} onAdd={()=>setAccountOpen(true)} onOpen={setAccountId}/>:<AccountWorkspace account={selected} stats={stats} equity={equity} setups={setups} calendar={calendar} visible={visible} query={query} setQuery={setQuery} onBack={()=>setAccountId(null)} onTrade={()=>setTradeOpen(true)} onCsv={csv}/>} 
 <PropAccountDialog open={accountOpen} saving={saving} onOpenChange={setAccountOpen} onSave={saveAccount}/>
 <TradeDialog open={tradeOpen} saving={saving} account={selected} onOpenChange={setTradeOpen} onSave={saveTrade}/>
 </div>;
}

function AllAccounts({summaries,onAdd,onOpen}:{summaries:Array<{account:PropAccount;trades:number;pnl:number;winRate:number;target:number;dd:number}>;onAdd:()=>void;onOpen:(id:string)=>void}){
 const total=summaries.reduce((s,a)=>s+a.pnl,0),capital=summaries.reduce((s,a)=>s+a.account.accountSize,0);
 return <div className="mx-auto max-w-[1500px] space-y-6 p-4 lg:p-8"><div className="flex items-end gap-4"><div><Badge variant="outline" className="mb-3 border-cyan-400/20 text-cyan-300"><ShieldCheck/> Trading workspace</Badge><h1 className="text-3xl font-black">All accounts</h1><p className="mt-1 text-sm text-muted-foreground">Barcha prop challenge va funded accountlaringiz.</p></div><Button className="ml-auto" size="lg" onClick={onAdd}><Plus/> Prop account qo&apos;shish</Button></div>
 <div className="grid gap-4 md:grid-cols-3"><Stat title="Jami kapital" value={money.format(capital)} icon={WalletCards}/><Stat title="Umumiy P&L" value={`${total>=0?"+":""}${money.format(total)}`} icon={total>=0?TrendingUp:TrendingDown}/><Stat title="Active accounts" value={String(summaries.filter(s=>s.account.status==="Active").length)} icon={ShieldCheck}/></div>
 {!summaries.length?<Card className="min-h-80 justify-center border-dashed text-center"><CardContent><WalletCards className="mx-auto size-10 text-cyan-300"/><h2 className="mt-4 text-xl font-bold">Prop account qo&apos;shing</h2><p className="mt-2 text-muted-foreground">Har bir account uchun alohida jurnal va statistika yaratiladi.</p><Button className="mt-5" onClick={onAdd}><Plus/> Account yaratish</Button></CardContent></Card>:<div className="grid gap-5 lg:grid-cols-2 2xl:grid-cols-3">{summaries.map(s=><Card key={s.account.id} className="bg-card/75 transition hover:-translate-y-1 hover:ring-cyan-300/25"><CardHeader><div className="flex items-start"><div><CardTitle className="text-xl">{s.account.name}</CardTitle><CardDescription className="mt-1">{s.account.firm||"Independent"} / {s.account.phase} / {s.account.marketType}</CardDescription></div><Badge variant="outline" className="ml-auto text-cyan-300">{s.account.status}</Badge></div></CardHeader><CardContent className="space-y-5"><div><p className="text-xs text-muted-foreground">Account natijasi</p><p className={`mt-1 font-mono text-3xl font-black ${s.pnl>=0?"text-emerald-300":"text-rose-300"}`}>{s.pnl>=0?"+":""}{money.format(s.pnl)}</p></div><div className="grid grid-cols-3 rounded-xl bg-background/50 p-3 text-center"><Mini label="SIZE" value={money.format(s.account.accountSize)}/><Mini label="TRADES" value={String(s.trades)}/><Mini label="WIN RATE" value={`${s.winRate}%`}/></div><Progress label="Profit target" value={s.target} color="bg-emerald-400"/><Progress label="Drawdown used" value={s.dd} color="bg-rose-400"/></CardContent><CardFooter><Button variant="secondary" className="w-full" onClick={()=>onOpen(s.account.id)}>Jurnalni ochish <ChevronRight/></Button></CardFooter></Card>)}</div>}</div>;
}

function AccountWorkspace({account,stats,equity,setups,calendar,visible,query,setQuery,onBack,onTrade,onCsv}:{account:PropAccount;stats:{pnl:number;wins:number;losses:number;winRate:number;avgR:number;pf:number};equity:Array<{trade:number;equity:number}>;setups:Array<{name:string;pnl:number;trades:number;wins:number;rate:number}>;calendar:Array<{day:number;trades:JournalEntry[];pnl:number}|null>;visible:JournalEntry[];query:string;setQuery:(v:string)=>void;onBack:()=>void;onTrade:()=>void;onCsv:()=>void}){
 return <div className="mx-auto max-w-[1600px]"><header className="sticky top-0 z-20 flex items-center gap-3 border-b bg-background/85 px-4 py-3 backdrop-blur-xl lg:px-8"><Button variant="ghost" size="icon" onClick={onBack}><ArrowLeft/></Button><div><h1 className="text-xl font-black">{account.name}</h1><p className="text-xs text-muted-foreground">{account.firm||"Independent"} / {account.phase} / {money.format(account.accountSize)}</p></div><Badge variant="outline" className="ml-3 hidden text-cyan-300 sm:flex">{account.status}</Badge><Button variant="outline" className="ml-auto" onClick={onCsv}><Download/> CSV</Button><Button onClick={onTrade}><Plus/> Trade qo&apos;shish</Button></header><div className="space-y-5 p-4 lg:p-8"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat title="Monthly P&L" value={`${stats.pnl>=0?"+":""}${money.format(stats.pnl)}`} icon={stats.pnl>=0?TrendingUp:TrendingDown}/><Stat title="Win rate" value={`${stats.winRate}%`} icon={Target}/><Stat title="Average R" value={`${stats.avgR.toFixed(2)}R`} icon={BarChart3}/><Stat title="Profit factor" value={stats.pf.toFixed(2)} icon={TrendingUp}/><Stat title="Wins / Losses" value={`${stats.wins} / ${stats.losses}`} icon={CalendarDays}/></div>
 <Tabs defaultValue="overview" className="gap-5"><TabsList className="h-11 w-full justify-start overflow-x-auto bg-card p-1"><TabsTrigger value="overview" className="px-6">Overview</TabsTrigger><TabsTrigger value="calendar" className="px-6">Calendar</TabsTrigger><TabsTrigger value="trades" className="px-6">Trades</TabsTrigger><TabsTrigger value="analytics" className="px-6">Analytics</TabsTrigger></TabsList>
 <TabsContent value="overview" className="grid gap-5 xl:grid-cols-[1.5fr_.5fr]"><Card><CardHeader><CardTitle>Account equity</CardTitle><CardDescription>Boshlang&apos;ich balansdan cumulative natija</CardDescription></CardHeader><CardContent className="h-80">{equity.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={equity}><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="trade"/><YAxis width={70}/><Tooltip formatter={v=>money.format(Number(v))}/><Area dataKey="equity" stroke="#22d3ee" fill="#22d3ee33" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<Empty text="Equity curve uchun trade qo'shing."/>}</CardContent></Card><Card><CardHeader><CardTitle>Challenge limits</CardTitle><CardDescription>Risk nazorati</CardDescription></CardHeader><CardContent className="space-y-6"><Progress label="Profit target" value={account.profitTarget?Math.min(100,Math.max(0,stats.pnl/account.profitTarget*100)):0} color="bg-emerald-400"/><Progress label="Max drawdown" value={account.maxDrawdown&&stats.pnl<0?Math.min(100,Math.abs(stats.pnl)/account.maxDrawdown*100):0} color="bg-rose-400"/><div className="grid grid-cols-2 gap-3"><Mini label="DAILY LIMIT" value={money.format(account.dailyDrawdown)}/><Mini label="START BALANCE" value={money.format(account.initialBalance)}/></div></CardContent></Card></TabsContent>
 <TabsContent value="calendar"><Card className="overflow-x-auto"><CardContent className="min-w-[760px]"><div className="grid grid-cols-7">{days.map(d=><div key={d} className="py-3 text-center text-xs text-muted-foreground">{d}</div>)}</div><div className="grid grid-cols-7 gap-1">{calendar.map((c,i)=>c?<div key={c.day} className={`min-h-28 rounded-lg border p-3 ${c.trades.length?c.pnl>=0?"bg-emerald-400/5":"bg-rose-400/5":"bg-background/30"}`}><span className="text-xs text-muted-foreground">{c.day}</span>{c.trades.length?<><b className={`mt-4 block font-mono ${c.pnl>=0?"text-emerald-300":"text-rose-300"}`}>{money.format(c.pnl)}</b><small>{c.trades.length} trade</small></>:null}</div>:<div key={i}/>)}</div></CardContent></Card></TabsContent>
 <TabsContent value="trades"><Card><CardHeader><div className="flex items-center"><div><CardTitle>Trade journal</CardTitle><CardDescription>{visible.length} ta trade</CardDescription></div><div className="relative ml-auto w-72"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="pl-9" placeholder="Symbol yoki setup"/></div></div></CardHeader><CardContent className="px-0">{visible.length?visible.map(e=><div key={e.id} className="flex items-center gap-4 border-t px-5 py-4">{e.imageUrl?<img src={e.imageUrl} alt="" className="h-14 w-20 rounded-lg object-cover"/>:<span className="grid h-14 w-20 place-items-center rounded-lg bg-muted"><ImageIcon/></span>}<div><b>{e.symbol}</b><p className="text-xs text-muted-foreground">{e.side} / {e.setup||"No setup"} / {e.date}</p></div><div className="ml-auto text-right"><b className={e.pnl>=0?"text-emerald-300":"text-rose-300"}>{money.format(e.pnl)}</b><p className="text-xs">{(e.resultR||0).toFixed(2)}R</p></div></div>):<Empty text="Bu accountda trade yo'q."/>}</CardContent></Card></TabsContent>
 <TabsContent value="analytics" className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>Setup performance</CardTitle><CardDescription>Strategiyalar bo&apos;yicha natija</CardDescription></CardHeader><CardContent className="space-y-5">{setups.length?setups.map(s=><div key={s.name}><div className="flex text-sm"><span>{s.name}</span><b className="ml-auto">{s.rate}% / {money.format(s.pnl)}</b></div><Progress label={`${s.trades} trades`} value={s.rate} color="bg-cyan-400"/></div>):<Empty text="Setup statistikasi yo'q."/>}</CardContent></Card><Card><CardHeader><CardTitle>Account details</CardTitle><CardDescription>Prop challenge konfiguratsiyasi</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-4"><Mini label="FIRM" value={account.firm||"Independent"}/><Mini label="PHASE" value={account.phase}/><Mini label="MARKET" value={account.marketType}/><Mini label="START DATE" value={account.startDate}/><Mini label="TARGET" value={money.format(account.profitTarget)}/><Mini label="MAX DD" value={money.format(account.maxDrawdown)}/></CardContent></Card></TabsContent></Tabs></div></div>;
}

function TradeDialog({open,saving,account,onOpenChange,onSave}:{open:boolean;saving:boolean;account:PropAccount|null;onOpenChange:(v:boolean)=>void;onSave:(f:FormData)=>void|Promise<void>}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Yangi trade</DialogTitle><DialogDescription>{account?.name}</DialogDescription></DialogHeader><form action={onSave} className="grid gap-4 sm:grid-cols-2">{[["Symbol","symbol","XAUUSD"],["Setup","setup","London breakout"],["Entry","entry",""],["Exit","exit",""],["Lot / miqdor","quantity","1"],["Risk","riskAmount","100"],["Komissiya","fees","0"],["Tags","tags","London, BOS"]].map(([l,n,p])=><div key={n} className="space-y-2"><Label>{l}</Label><Input name={n} placeholder={p} type={["entry","exit","quantity","riskAmount","fees"].includes(n)?"number":"text"} step="any" required={["symbol","entry","exit","quantity"].includes(n)}/></div>)}<div className="space-y-2"><Label>Yo&apos;nalish</Label><select name="side" className="h-9 w-full rounded-lg border bg-background px-3"><option>Long</option><option>Short</option></select></div><div className="space-y-2"><Label>Sana</Label><Input name="tradedAt" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="space-y-2"><Label>Emotsiya</Label><Input name="emotion" defaultValue="Neutral"/></div><div className="space-y-2 sm:col-span-2"><Label>Review</Label><Textarea name="note"/></div><Button disabled={saving} className="sm:col-span-2">{saving?<LoaderCircle className="animate-spin"/>:<Plus/>} Trade saqlash</Button></form></DialogContent></Dialog>}
function Stat({title,value,icon:Icon}:{title:string;value:string;icon:typeof Target}){return <Card><CardContent><Icon className="size-5 text-cyan-300"/><p className="mt-4 text-xs uppercase tracking-wider text-muted-foreground">{title}</p><p className="mt-1 font-mono text-2xl font-black">{value}</p></CardContent></Card>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-background/50 p-3 text-center"><b className="block truncate font-mono">{value}</b><small className="text-[10px] text-muted-foreground">{label}</small></div>}
function Progress({label,value,color}:{label:string;value:number;color:string}){return <div><div className="mb-2 flex text-xs"><span className="text-muted-foreground">{label}</span><b className="ml-auto">{value.toFixed(0)}%</b></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${color}`} style={{width:`${value}%`}}/></div></div>}
function Empty({text}:{text:string}){return <div className="grid min-h-40 place-items-center text-sm text-muted-foreground">{text}</div>}
