const classes = (...values: string[]) => values.join(" ");

export const APP_ROOT_TAILWIND_CLASS = classes(
  "min-h-dvh w-full overflow-x-hidden bg-black text-[#f4f4f5] antialiased [font-synthesis:none] [text-rendering:optimizeLegibility]",
  "[&_*]:min-w-0 [&_*]:[scrollbar-width:thin] [&_*]:[scrollbar-color:#2a2a2a_#050505]",
  "[&_*::-webkit-scrollbar]:size-[10px] [&_*::-webkit-scrollbar-track]:bg-[#050505]",
  "[&_*::-webkit-scrollbar-thumb]:rounded-full [&_*::-webkit-scrollbar-thumb]:border-2 [&_*::-webkit-scrollbar-thumb]:border-[#050505] [&_*::-webkit-scrollbar-thumb]:bg-[#242424] hover:[&_*::-webkit-scrollbar-thumb]:bg-[#303030]",
  "[&_*::-webkit-scrollbar-corner]:bg-[#050505]",
  "[&_button]:touch-manipulation [&_[role='button']]:touch-manipulation",
  "[&_img]:max-w-full [&_video]:max-w-full [&_canvas]:max-w-full [&_svg]:max-w-full",
  "[&_button]:[overflow-wrap:anywhere] [&_a]:[overflow-wrap:anywhere] [&_p]:[overflow-wrap:anywhere] [&_span]:[overflow-wrap:anywhere] [&_strong]:[overflow-wrap:anywhere] [&_small]:[overflow-wrap:anywhere]",
  "[&_h1]:[overflow-wrap:anywhere] [&_h2]:[overflow-wrap:anywhere] [&_h3]:[overflow-wrap:anywhere] [&_h4]:[overflow-wrap:anywhere] [&_h5]:[overflow-wrap:anywhere] [&_h6]:[overflow-wrap:anywhere]",
  "[&_table]:w-full [&_table]:max-w-full [&_table]:border-collapse",
  "[&_.overflow-x-auto]:[overscroll-behavior-inline:contain] [&_.overflow-x-auto]:[-webkit-overflow-scrolling:touch]",
  "[&_[data-slot='table-container']]:[overscroll-behavior-inline:contain] [&_[data-slot='table-container']]:[-webkit-overflow-scrolling:touch]",
  "[&_.recharts-responsive-container]:max-w-full [&_.recharts-wrapper]:max-w-full [&_.recharts-surface]:max-w-full [&_.recharts-wrapper]:overflow-hidden",
  "[&_[data-radix-popper-content-wrapper]]:!max-w-[calc(100vw-16px)]",
  "[&_[data-slot='dropdown-menu-content']]:!max-w-[calc(100vw-16px)] [&_[data-slot='dropdown-menu-sub-content']]:!max-w-[calc(100vw-16px)]",
  "[&_[data-slot='select-content']]:!max-w-[calc(100vw-16px)] [&_[data-slot='popover-content']]:!max-w-[calc(100vw-16px)]",
  "[&_[data-slot='dialog-overlay']]:!bg-black/[.92] [&_[data-slot='dialog-overlay']]:!backdrop-blur-none",
  "[&_[data-slot='alert-dialog-overlay']]:!bg-black/[.92] [&_[data-slot='alert-dialog-overlay']]:!backdrop-blur-none",
  "[&_[data-slot='dialog-content']]:!w-[min(calc(100vw-20px),var(--dialog-max-width,900px))] [&_[data-slot='dialog-content']]:!max-w-[calc(100vw-20px)] [&_[data-slot='dialog-content']]:!max-h-[calc(100dvh-20px)] [&_[data-slot='dialog-content']]:overflow-y-auto",
  "[&_[data-slot='alert-dialog-content']]:!w-[min(calc(100vw-20px),var(--dialog-max-width,900px))] [&_[data-slot='alert-dialog-content']]:!max-w-[calc(100vw-20px)] [&_[data-slot='alert-dialog-content']]:!max-h-[calc(100dvh-20px)] [&_[data-slot='alert-dialog-content']]:overflow-y-auto",
  "[&_[data-slot='dialog-content']]:[-webkit-overflow-scrolling:touch] [&_[data-slot='alert-dialog-content']]:[-webkit-overflow-scrolling:touch]",
  "[&_[data-slot='dropdown-menu-content']]:!z-[9999] [&_[data-slot='select-content']]:!z-[9999] [&_[data-slot='popover-content']]:!z-[9999]",
  "[&_[data-slot='dropdown-menu-content']]:!min-w-[178px] [&_[data-slot='select-content']]:!min-w-[178px] [&_[data-slot='popover-content']]:!min-w-[178px]",
  "[&_[data-slot='dropdown-menu-content']]:!border-white/[.085] [&_[data-slot='select-content']]:!border-white/[.085] [&_[data-slot='popover-content']]:!border-white/[.085]",
  "[&_[data-slot='dropdown-menu-content']]:!bg-[#080808] [&_[data-slot='select-content']]:!bg-[#080808] [&_[data-slot='popover-content']]:!bg-[#080808]",
  "[&_[data-slot='dropdown-menu-content']]:!shadow-[0_18px_55px_rgba(0,0,0,.52)] [&_[data-slot='select-content']]:!shadow-[0_18px_55px_rgba(0,0,0,.52)] [&_[data-slot='popover-content']]:!shadow-[0_18px_55px_rgba(0,0,0,.52)]",
  "[&_[data-slot='dropdown-menu-item']]:!rounded-xl [&_[data-slot='select-item']]:!rounded-xl",
  "[&_[data-slot='dropdown-menu-item'][data-highlighted]]:!bg-white/[.07] [&_[data-slot='dropdown-menu-item'][data-highlighted]]:!text-white",
  "[&_[data-slot='select-item'][data-highlighted]]:!bg-white/[.07] [&_[data-slot='select-item'][data-highlighted]]:!text-white",
  "[&_.tw-account-settings-item]:!text-zinc-200 hover:[&_.tw-account-settings-item]:!bg-white/[.065]",
  "[&_.tw-account-settings-item+[role='menuitem']]:mt-0.5 [&_.tw-account-settings-item+[role='menuitem']]:border-t [&_.tw-account-settings-item+[role='menuitem']]:border-white/[.07] [&_.tw-account-settings-item+[role='menuitem']]:!pt-[.55rem]",
  "[&_.animate-page-in]:animate-in [&_.animate-page-in]:fade-in [&_.animate-page-in]:slide-in-from-bottom-2 [&_.animate-page-in]:duration-300",
  "[&_.glass]:border [&_.glass]:border-white/[.08] [&_.glass]:bg-[#0b0b0b] [&_.glass]:shadow-[0_12px_36px_rgba(0,0,0,.24)]",
  "[&_.glass-soft]:border [&_.glass-soft]:border-white/[.07] [&_.glass-soft]:bg-[#080808] [&_.glass-soft]:shadow-[0_10px_28px_rgba(0,0,0,.2)]",
  "[&_.glass-strong]:border [&_.glass-strong]:border-white/[.08] [&_.glass-strong]:bg-[#0b0b0b] [&_.glass-strong]:shadow-[0_18px_48px_rgba(0,0,0,.28)]",
  "[&_.surface]:rounded-[1.35rem] [&_.surface]:border [&_.surface]:border-white/[.08] [&_.surface]:bg-[#0b0b0b] [&_.surface]:shadow-[0_14px_38px_rgba(0,0,0,.24)]",
  "[&_.surface-soft]:rounded-[1.35rem] [&_.surface-soft]:border [&_.surface-soft]:border-white/[.06] [&_.surface-soft]:bg-[#080808] [&_.surface-soft]:shadow-[0_10px_28px_rgba(0,0,0,.2)]",
  "[&_.surface-strong]:rounded-[1.75rem] [&_.surface-strong]:border [&_.surface-strong]:border-white/[.09] [&_.surface-strong]:bg-[#0b0b0b] [&_.surface-strong]:shadow-[0_18px_48px_rgba(0,0,0,.32)]",
  "[&_.premium-border]:border [&_.premium-border]:border-white/[.08] [&_.premium-text-dim]:text-white/[.62] [&_.premium-shadow]:shadow-[0_18px_58px_rgba(0,0,0,.46)]",
  "[&_[class*='bg-[#171717]']]:!bg-[#0b0b0b] [&_[class*='bg-[#111111]']]:!bg-[#0b0b0b] [&_[class*='bg-[#101010]']]:!bg-[#0b0b0b]",
  "[&_[class*='bg-[#0d0d0d]']]:!bg-[#0b0b0b] [&_[class*='bg-[#0b0b0b]']]:!bg-[#0b0b0b] [&_[class*='bg-[#070707]']]:!bg-[#0b0b0b]",
  "[&_[class*='bg-[#171717]']]:!border-white/[.08] [&_[class*='bg-[#111111]']]:!border-white/[.08] [&_[class*='bg-[#101010]']]:!border-white/[.08]",
  "[&_[class*='bg-[#0d0d0d]']]:!border-white/[.08] [&_[class*='bg-[#0b0b0b]']]:!border-white/[.08] [&_[class*='bg-[#070707]']]:!border-white/[.08]",
  "[&_[class*='backdrop-blur']]:!backdrop-blur-none [&_[class*='border-border']]:!border-white/[.08] [&_[class*='bg-card']]:!bg-[#0b0b0b]",
  "[&_[class*='text-slate-500']]:!text-white/[.46] [&_[class*='text-zinc-500']]:!text-white/[.46]",
  "[&_article_a:has(img[alt='Post_media'])]:!min-h-0 [&_article_a:has(img[alt='Post_media'])]:!aspect-[16/10] [&_article_a:has(img[alt='Post_media'])]:!max-h-[360px] [&_article_a:has(img[alt='Post_media'])]:!rounded-2xl",
  "[&_article_a:has(img[alt*='Trade_media'])]:!min-h-0 [&_article_a:has(img[alt*='Trade_media'])]:!aspect-[16/10] [&_article_a:has(img[alt*='Trade_media'])]:!max-h-[360px] [&_article_a:has(img[alt*='Trade_media'])]:!rounded-2xl",
  "[&_article_img[alt='Post_media']]:!max-h-[360px] [&_article_img[alt='Post_media']]:!object-cover [&_article_img[alt='Trade_media']]:!max-h-[360px] [&_article_img[alt='Trade_media']]:!object-cover",
  "max-sm:[&_article_a:has(img[alt='Post_media'])]:!max-h-[260px] max-sm:[&_article_a:has(img[alt*='Trade_media'])]:!max-h-[260px]",
  "max-sm:[&_article_img[alt='Post_media']]:!max-h-[260px] max-sm:[&_article_img[alt='Trade_media']]:!max-h-[260px]",
  "max-[480px]:[&_[data-slot='dialog-content']]:!w-[calc(100vw-10px)] max-[480px]:[&_[data-slot='dialog-content']]:!max-w-[calc(100vw-10px)] max-[480px]:[&_[data-slot='dialog-content']]:!max-h-[calc(100dvh-10px)] max-[480px]:[&_[data-slot='dialog-content']]:!rounded-2xl",
  "max-[480px]:[&_[data-slot='alert-dialog-content']]:!w-[calc(100vw-10px)] max-[480px]:[&_[data-slot='alert-dialog-content']]:!max-w-[calc(100vw-10px)] max-[480px]:[&_[data-slot='alert-dialog-content']]:!max-h-[calc(100dvh-10px)] max-[480px]:[&_[data-slot='alert-dialog-content']]:!rounded-2xl",
  "max-[480px]:[&_[data-slot='dialog-content']_input]:text-base max-[480px]:[&_[data-slot='dialog-content']_textarea]:text-base max-[480px]:[&_[data-slot='dialog-content']_select]:text-base max-[480px]:[&_[data-slot='dialog-content']_button]:text-base",
);

export const WORKSPACE_TAILWIND_CLASS = classes(
  "workspace-shell flex h-dvh w-full overflow-clip bg-black p-0 text-foreground lg:gap-0",
  "[&_[data-workspace-main]]:[scrollbar-gutter:stable] [&_[data-workspace-main]]:[-webkit-overflow-scrolling:touch]",
  "[&_[data-workspace-main]>section]:w-full [&_[data-workspace-main]>section]:bg-black [&_[data-workspace-main]>section]:text-[#fafafa]",
  "[&_.text-zinc-700]:!text-[#777781] [&_.text-zinc-600]:!text-[#90909a] [&_.text-zinc-500]:!text-[#a8a8b2] [&_.text-zinc-400]:!text-[#c6c6ce] [&_.text-zinc-300]:!text-[#e4e4e7]",
  "[&_[class*='text-blue-']]:!text-zinc-300 [&_[class*='text-sky-']]:!text-zinc-300 [&_[class*='text-cyan-']]:!text-zinc-300 [&_[class*='text-indigo-']]:!text-zinc-300",
  "[&_[class*='text-violet-']]:!text-zinc-300 [&_[class*='text-purple-']]:!text-zinc-300 [&_[class*='text-fuchsia-']]:!text-zinc-300 [&_[class*='text-amber-']]:!text-zinc-300 [&_[class*='text-yellow-']]:!text-zinc-300",
  "[&_[class*='bg-blue-']]:!bg-white/[.055] [&_[class*='bg-sky-']]:!bg-white/[.055] [&_[class*='bg-cyan-']]:!bg-white/[.055] [&_[class*='bg-indigo-']]:!bg-white/[.055]",
  "[&_[class*='bg-violet-']]:!bg-white/[.055] [&_[class*='bg-purple-']]:!bg-white/[.055] [&_[class*='bg-fuchsia-']]:!bg-white/[.055] [&_[class*='bg-amber-']]:!bg-white/[.055] [&_[class*='bg-yellow-']]:!bg-white/[.055]",
  "[&_[class*='border-blue-']]:!border-white/[.17] [&_[class*='border-sky-']]:!border-white/[.17] [&_[class*='border-cyan-']]:!border-white/[.17] [&_[class*='border-indigo-']]:!border-white/[.17]",
  "[&_[class*='border-violet-']]:!border-white/[.17] [&_[class*='border-purple-']]:!border-white/[.17] [&_[class*='border-fuchsia-']]:!border-white/[.17] [&_[class*='border-amber-']]:!border-white/[.17] [&_[class*='border-yellow-']]:!border-white/[.17]",
  "[&_.text-emerald-300]:!text-[#34d399] [&_.text-emerald-400]:!text-[#34d399] [&_.text-green-300]:!text-[#34d399] [&_.text-green-400]:!text-[#34d399]",
  "[&_.text-rose-300]:!text-[#fb7185] [&_.text-rose-400]:!text-[#fb7185] [&_.text-red-300]:!text-[#fb7185] [&_.text-red-400]:!text-[#fb7185]",
  "[&>[data-workspace-main]]:h-dvh [&>[data-workspace-main]]:min-w-0 [&>[data-workspace-main]]:flex-1 [&>[data-workspace-main]]:overflow-x-hidden [&>[data-workspace-main]]:overflow-y-auto [&>[data-workspace-main]]:overscroll-contain [&>[data-workspace-main]]:border-0 [&>[data-workspace-main]]:rounded-none [&>[data-workspace-main]]:bg-black",
  "lg:[&>aside]:top-0 lg:[&>aside]:left-0 lg:[&>aside]:h-dvh lg:[&>aside]:rounded-none lg:[&>aside]:border-0 lg:[&>aside]:shadow-none",
  "lg:[&>aside:not([data-community-sidebar])]:!w-[252px] lg:[&>aside:not([data-community-sidebar])]:!p-[.85rem] lg:[&>aside:not([data-community-sidebar])]:!border-r lg:[&>aside:not([data-community-sidebar])]:!border-r-white/[.1]",
  "lg:[&>aside:not([data-community-sidebar])]:!bg-black",
  "lg:[&>aside:not([data-community-sidebar])+div[aria-hidden='true']]:!w-[252px]",
  "lg:[&>aside[data-community-sidebar]]:!p-0 lg:[&>aside[data-community-sidebar]]:!border-r lg:[&>aside[data-community-sidebar]]:!border-r-white/[.075]",
  "lg:[&>aside[data-community-sidebar='collapsed']]:!w-[76px] lg:[&>aside[data-community-sidebar='expanded']]:!w-[236px]",
  "lg:[&>aside[data-community-sidebar='collapsed']+div[aria-hidden='true']]:!w-[76px] lg:[&>aside[data-community-sidebar='expanded']+div[aria-hidden='true']]:!w-[236px]",
  "[&>aside[data-community-sidebar]+div[aria-hidden='true']]:transition-[width] [&>aside[data-community-sidebar]+div[aria-hidden='true']]:duration-200 [&>aside[data-community-sidebar]+div[aria-hidden='true']]:ease-out",
  "[&>aside_button[aria-label='TradeWay_home']]:min-h-[3.75rem] [&>aside_button[aria-label='TradeWay_home']]:!rounded-2xl [&>aside_button[aria-label='TradeWay_home']]:!border [&>aside_button[aria-label='TradeWay_home']]:border-transparent [&>aside_button[aria-label='TradeWay_home']]:!p-[.5rem_.55rem]",
  "hover:[&>aside_button[aria-label='TradeWay_home']]:!border-white/[.09] hover:[&>aside_button[aria-label='TradeWay_home']]:!bg-white/[.035]",
  "[&>aside_button[aria-label='TradeWay_home']>span:first-child]:!size-11 [&>aside_button[aria-label='TradeWay_home']>span:first-child]:!rounded-[.9rem] [&>aside_button[aria-label='TradeWay_home']>span:first-child]:!border-white/[.14]",
  "[&>aside_button[aria-label='TradeWay_home']>span:first-child]:!bg-[#111111] [&>aside_button[aria-label='TradeWay_home']>span:first-child]:!shadow-none",
  "[&>aside_button[aria-label='TradeWay_home']_img]:!object-contain [&>aside_button[aria-label='TradeWay_home']_img]:scale-[.92] [&>aside_button[aria-label='TradeWay_home']_img]:contrast-105 [&>aside_button[aria-label='TradeWay_home']_img]:brightness-110",
  "[&>aside_button[aria-label='TradeWay_home']_strong]:!text-[.94rem] [&>aside_button[aria-label='TradeWay_home']_strong]:!font-[750] [&>aside_button[aria-label='TradeWay_home']_strong]:!tracking-[-.025em] [&>aside_button[aria-label='TradeWay_home']_strong]:!text-white",
  "[&>aside_button[aria-label='TradeWay_home']_small]:mt-[.16rem] [&>aside_button[aria-label='TradeWay_home']_small]:block [&>aside_button[aria-label='TradeWay_home']_small]:!text-[.68rem] [&>aside_button[aria-label='TradeWay_home']_small]:font-[550] [&>aside_button[aria-label='TradeWay_home']_small]:!text-[#9a9aa4]",
  "[&>aside>div[class*='mt-4']]:min-h-[3.25rem] [&>aside>div[class*='mt-4']]:!border-white/[.11] [&>aside>div[class*='mt-4']]:!bg-[#090909] [&>aside>div[class*='mt-4']]:shadow-[inset_0_1px_0_rgba(255,255,255,.035)]",
  "hover:[&>aside>div[class*='mt-4']]:!border-white/[.17] hover:[&>aside>div[class*='mt-4']]:!bg-[#101310]",
  "[&>aside>div.mt-3>p]:!pt-4 [&>aside>div.mt-3>p]:!pb-[.38rem] [&>aside>div.mt-3>p]:!text-[.59rem] [&>aside>div.mt-3>p]:!font-[750] [&>aside>div.mt-3>p]:!tracking-[.18em] [&>aside>div.mt-3>p]:!text-[#8d8d97]",
  "[&>aside_nav]:grid [&>aside_nav]:gap-[.22rem]",
  "[&>aside_nav>button]:min-h-[2.72rem] [&>aside_nav>button]:!gap-[.68rem] [&>aside_nav>button]:!rounded-[.82rem] [&>aside_nav>button]:!border [&>aside_nav>button]:border-transparent [&>aside_nav>button]:!p-[.42rem_.58rem] [&>aside_nav>button]:!text-[#c4c4cc]",
  "hover:[&>aside_nav>button]:!border-white/[.08] hover:[&>aside_nav>button]:!bg-white/[.045] hover:[&>aside_nav>button]:!text-white",
  "[&>aside_nav>button[class*='ring-white/10']]:!border-white/[.13] [&>aside_nav>button[class*='ring-white/10']]:!bg-[#1a1a1a] [&>aside_nav>button[class*='ring-white/10']]:!text-white [&>aside_nav>button[class*='ring-white/10']]:!shadow-[inset_3px_0_0_#34d399,inset_0_1px_0_rgba(255,255,255,.045)]",
  "[&>aside_nav>button>span:first-child]:!size-[1.95rem] [&>aside_nav>button>span:first-child]:!rounded-[.65rem] [&>aside_nav>button>span:first-child]:!border [&>aside_nav>button>span:first-child]:border-white/[.065] [&>aside_nav>button>span:first-child]:!bg-[#0b0d0c] [&>aside_nav>button>span:first-child]:!text-[#a8a8b2]",
  "hover:[&>aside_nav>button>span:first-child]:!border-emerald-300/[.22] hover:[&>aside_nav>button>span:first-child]:!bg-emerald-300/[.08] hover:[&>aside_nav>button>span:first-child]:!text-slate-50",
  "[&>aside_nav>button[class*='ring-white/10']>span:first-child]:!border-emerald-300/[.22] [&>aside_nav>button[class*='ring-white/10']>span:first-child]:!bg-emerald-300/[.08] [&>aside_nav>button[class*='ring-white/10']>span:first-child]:!text-slate-50",
  "[&>aside_nav>button>span:last-child]:!text-[.87rem] [&>aside_nav>button>span:last-child]:!font-[620] [&>aside_nav>button>span:last-child]:tracking-[-.012em]",
  "[&>aside>div.mt-auto>div]:min-h-[3.65rem] [&>aside>div.mt-auto>div]:!border-white/[.11] [&>aside>div.mt-auto>div]:!bg-[#090909] hover:[&>aside>div.mt-auto>div]:!border-white/[.18] hover:[&>aside>div.mt-auto>div]:!bg-[#111411]",
  "[&>aside>div.mt-auto_strong]:!text-[.78rem] [&>aside>div.mt-auto_strong]:!text-zinc-100 [&>aside>div.mt-auto_small]:!text-[.68rem] [&>aside>div.mt-auto_small]:!text-[#9a9aa4]",
  "[&_.tw-app-topbar]:top-0 [&_.tw-app-topbar]:min-h-[3.75rem] [&_.tw-app-topbar]:!rounded-none [&_.tw-app-topbar]:!border-white/[.1] [&_.tw-app-topbar]:!bg-black [&_.tw-app-topbar]:!shadow-none",
  "[&_[data-slot='card']]:!border-white/[.1] [&_[data-slot='card']]:!bg-[#0a0a0a] [&_[data-slot='card']]:!shadow-[inset_0_1px_0_rgba(255,255,255,.025),0_16px_42px_rgba(0,0,0,.18)]",
  "[&_[data-slot='card']]:transition-[border-color,background-color,transform] [&_[data-slot='card']]:duration-200 hover:[&_[data-slot='card']]:!border-white/[.145]",
  "[&_[data-slot='card-header']]:!border-white/[.085]",
  "[&_input]:!border-white/[.11] [&_textarea]:!border-white/[.11] [&_[data-slot='select-trigger']]:!border-white/[.11] [&_input]:!bg-[#0a0c0b] [&_textarea]:!bg-[#0a0c0b] [&_[data-slot='select-trigger']]:!bg-[#0a0c0b]",
  "hover:[&_input]:!border-white/[.17] hover:[&_textarea]:!border-white/[.17] hover:[&_[data-slot='select-trigger']]:!border-white/[.17]",
  "[&_input::placeholder]:!text-[#777781] [&_textarea::placeholder]:!text-[#777781]",
  "[&_[data-slot='button']]:!rounded-xl [&_[data-slot='button']]:font-[650] [&_[data-slot='button']]:!shadow-none",
  "[&_[data-slot='button'][data-variant='outline']]:!border-white/[.11] [&_[data-slot='button'][data-variant='outline']]:!bg-[#090909] [&_[data-slot='button'][data-variant='outline']]:!text-[#ededf0]",
  "[&_[data-slot='button'][data-variant='secondary']]:!border-white/[.11] [&_[data-slot='button'][data-variant='secondary']]:!bg-[#090909] [&_[data-slot='button'][data-variant='secondary']]:!text-[#ededf0]",
  "hover:[&_[data-slot='button'][data-variant='outline']]:!border-white/[.18] hover:[&_[data-slot='button'][data-variant='outline']]:!bg-[#141714] hover:[&_[data-slot='button'][data-variant='secondary']]:!border-white/[.18] hover:[&_[data-slot='button'][data-variant='secondary']]:!bg-[#141714]",
  "[&_table_thead]:text-[#b7b7c0] [&_table_tbody_tr]:!border-white/[.075] [&_table_tbody_tr]:transition-colors [&_table_tbody_tr]:duration-150 hover:[&_table_tbody_tr]:bg-white/[.025]",
  "[&_main_header[class*='sticky'][class*='top-0'][class*='border-b']:not(.tw-app-topbar)]:hidden",
  "[&_main_header.tw-app-topbar[class*='sticky'][class*='top-0'][class*='border-b']]:block lg:[&_main_header.tw-app-topbar[class*='sticky'][class*='top-0'][class*='border-b']]:flex",
  "[&_main_header[class*='sticky'][class*='top-0'][class*='border-b']:not(.tw-app-topbar)+div]:!pt-6",
  "[&_section.overflow-hidden[class*='rounded-[24px]']]:hidden",
  "[&_.prop-card-glow]:!overflow-visible [&_.prop-card-glow]:!rounded-[1.1rem] [&_.prop-card-glow]:!border-white/[.085] [&_.prop-card-glow]:!bg-[#080808] [&_.prop-card-glow]:!shadow-none [&_.prop-card-glow]:transition-[border-color,background-color,transform] [&_.prop-card-glow]:duration-150",
  "hover:[&_.prop-card-glow]:!-translate-y-px hover:[&_.prop-card-glow]:!border-white/[.14] hover:[&_.prop-card-glow]:!bg-[#0b0b0b]",
  "[&_.prop-card-glow>div:first-child]:!p-4 [&_.prop-card-glow>div:last-child]:!bg-[#080808] [&_.prop-card-glow>div:last-child]:!p-[.72rem_1rem]",
  "[&_.prop-card-glow_[class*='text-2xl']]:!text-xl [&_.prop-card-glow_[class*='text-2xl']]:!leading-tight",
  "[&_.prop-card-glow_[class*='rounded-lg'][class*='border']]:!rounded-[.55rem]",
  "[&_.prop-card-glow_[class*='bg-[#121212]']]:!border-white/[.075] [&_.prop-card-glow_[class*='bg-[#121212]']]:!bg-white/[.025]",
  "[&_.prop-card-glow_[class*='bg-black/20']]:!border-white/[.075] [&_.prop-card-glow_[class*='bg-black/20']]:!bg-white/[.025]",
  "[&_.prop-card-glow_[class*='bg-black/15']]:!border-white/[.075] [&_.prop-card-glow_[class*='bg-black/15']]:!bg-white/[.025]",
  "[&_.prop-card-glow_[class*='bg-white/[.035]']]:!border-white/[.075] [&_.prop-card-glow_[class*='bg-white/[.035]']]:!bg-white/[.025]",
  "[&>aside_.mt-auto>div:first-child:not(:last-child)]:hidden [&>aside_div:has(>button[class*='Upgrade'])]:hidden",
  "max-lg:block max-lg:[&>[data-workspace-main]]:h-dvh max-lg:[&>[data-workspace-main]]:min-h-dvh max-lg:[&_[data-workspace-main]>section]:min-h-[calc(100dvh-3.75rem)]",
  "max-lg:[&_[data-workspace-main]_[class*='max-w-']]:max-w-full max-lg:[&_main>div]:max-w-full max-lg:[&_main_section]:max-w-full max-lg:[&_main_article]:max-w-full",
  "max-lg:[&_main_[class*='p-5']]:!px-4 max-lg:[&_main_[class*='p-7']]:!px-4 max-lg:[&_main_[class*='px-6']]:!px-4 max-lg:[&_main_[class*='px-7']]:!px-4",
  "max-lg:[&_main_[class*='rounded-[28px]']]:!rounded-[1.15rem] max-lg:[&_main_[class*='rounded-[26px]']]:!rounded-[1.15rem] max-lg:[&_main_[class*='rounded-[1.75rem]']]:!rounded-[1.15rem] max-lg:[&_main_[class*='rounded-[1.7rem]']]:!rounded-[1.15rem]",
  "max-md:[&_[data-workspace-main]]:pb-[max(.75rem,env(safe-area-inset-bottom))] max-md:[&_[data-workspace-main]>section]:min-h-[calc(100dvh-3.5rem)]",
  "max-md:[&_.tw-app-topbar]:min-h-14 max-md:[&_.tw-app-topbar]:!px-3",
  "max-md:[&_main_[class*='grid-cols-[']]:!grid-cols-1 max-md:[&_main_[class*='xl:grid-cols-']]:!grid-cols-1 max-md:[&_main_[class*='lg:grid-cols-']]:!grid-cols-1",
  "max-md:[&_main_[class*='min-h-[255px]']]:!min-h-[190px] max-md:[&_main_[class*='text-[2rem]']]:!text-[1.65rem] max-md:[&_main_[class*='text-[2rem]']]:!leading-[1.12]",
  "max-md:[&_main_.text-3xl]:!text-[1.55rem] max-md:[&_main_.text-3xl]:!leading-[1.16] max-md:[&_main_.text-2xl]:!text-[1.35rem] max-md:[&_main_.text-2xl]:!leading-[1.18]",
  "max-md:[&_main_table]:min-w-[680px] max-md:[&_main_[class*='overflow-hidden']:has(table)]:!overflow-x-auto max-md:[&_main_[class*='rounded']:has(table)]:!overflow-x-auto",
  "max-md:[&_[data-slot='dialog-content']]:!max-h-[calc(100dvh-14px)]",
  "max-sm:[&_main_[class*='sm:grid-cols-2']]:!grid-cols-1 max-sm:[&_main_[class*='sm:grid-cols-3']]:!grid-cols-1 max-sm:[&_[data-slot='dialog-content']_[class*='sm:grid-cols-2']]:!grid-cols-1 max-sm:[&_[data-slot='dialog-content']_[class*='sm:grid-cols-3']]:!grid-cols-1",
  "max-sm:[&_[data-slot='dialog-content']_[data-platform-grid]]:!grid-cols-2 max-sm:[&_main_[class*='sm:flex-row']]:!flex-col max-sm:[&_main_[class*='sm:flex-row']]:!items-stretch max-sm:[&_main_[class*='sm:items-center']]:!items-stretch",
  "max-[480px]:[&_main_[class*='p-4']]:!px-[.85rem] max-[480px]:[&_main_[class*='p-5']]:!px-[.85rem] max-[480px]:[&_main_[class*='p-6']]:!px-[.85rem] max-[480px]:[&_main_[class*='p-7']]:!px-[.85rem]",
  "max-[480px]:[&_main_[class*='gap-5']]:!gap-[.85rem] max-[480px]:[&_main_[class*='gap-6']]:!gap-[.85rem]",
  "[&_.calendar-workspace]:min-w-0 [&_.calendar-surface]:shadow-[inset_0_1px_0_rgba(255,255,255,.025)] [&_.calendar-day]:min-w-0",
  "max-md:[&_.calendar-summary-grid]:!grid-cols-3 max-md:[&_.calendar-summary-card]:min-h-[74px] max-md:[&_.calendar-toolbar]:gap-3 max-md:[&_.calendar-month-switcher]:w-full max-md:[&_.calendar-month-switcher_strong]:min-w-0 max-md:[&_.calendar-mobile-list_button]:min-h-[62px]",
  "md:max-lg:[&_.calendar-grid]:[grid-auto-rows:82px]",
  "lg:[&>aside[data-community-sidebar='collapsed']_nav]:!flex lg:[&>aside[data-community-sidebar='collapsed']_nav]:!flex-col lg:[&>aside[data-community-sidebar='collapsed']_nav]:!items-center lg:[&>aside[data-community-sidebar='collapsed']_nav]:!justify-start lg:[&>aside[data-community-sidebar='collapsed']_nav]:!gap-1.5",
  "lg:[&>aside[data-community-sidebar='expanded']_nav]:!block",
  "lg:[&>aside[data-community-sidebar]_nav>button]:!min-h-0 lg:[&>aside[data-community-sidebar]_nav>button]:!rounded-xl",
  "lg:[&>aside[data-community-sidebar='collapsed']_nav>button]:!grid lg:[&>aside[data-community-sidebar='collapsed']_nav>button]:!size-10 lg:[&>aside[data-community-sidebar='collapsed']_nav>button]:!place-items-center lg:[&>aside[data-community-sidebar='collapsed']_nav>button]:!gap-0 lg:[&>aside[data-community-sidebar='collapsed']_nav>button]:!p-0",
  "lg:[&>aside[data-community-sidebar='collapsed']_nav>button>span:first-child]:!absolute lg:[&>aside[data-community-sidebar='collapsed']_nav>button>span:first-child]:!inset-y-2 lg:[&>aside[data-community-sidebar='collapsed']_nav>button>span:first-child]:!left-0 lg:[&>aside[data-community-sidebar='collapsed']_nav>button>span:first-child]:!h-auto lg:[&>aside[data-community-sidebar='collapsed']_nav>button>span:first-child]:!w-0.5 lg:[&>aside[data-community-sidebar='collapsed']_nav>button>span:first-child]:!rounded-full lg:[&>aside[data-community-sidebar='collapsed']_nav>button>span:first-child]:!border-0 lg:[&>aside[data-community-sidebar='collapsed']_nav>button>span:first-child]:!bg-emerald-400 lg:[&>aside[data-community-sidebar='collapsed']_nav>button>span:first-child]:!p-0 lg:[&>aside[data-community-sidebar='collapsed']_nav>button>span:first-child]:!shadow-none",
  "lg:[&>aside[data-community-sidebar='expanded']_nav>button]:!min-h-10 lg:[&>aside[data-community-sidebar='expanded']_nav>button]:!p-[.45rem_.625rem]",
  "xl:[&_[data-community-sidebar]~[data-workspace-main]_div[class*='xl:grid-cols-[minmax(0,1.18fr)_minmax(300px,.82fr)]']]:items-start",
);
